### PR TITLE
Added after reduce code

### PR DESCRIPTION
**Pull request by yoavst**
## Features
* Added the possibility to run code after every reduce.
* Added the variables `$first` and `$last` to allow the after reduce code to easily get the line number. 

## Example usage
I'm building a compiler so this is an example from my code:
```java
after reduce {:
    int $$lineNumber = $first.left + 1;
    if (AST_Node.class.isInstance(RESULT)) {
        AST_Node ast = AST_Node.class.cast(RESULT);
        ast.lineNumber = $$lineNumber;
    } else if (AST_CALLABLE_VAR_CONT.class.isInstance(RESULT)) {
        AST_CALLABLE_VAR_CONT ast = AST_CALLABLE_VAR_CONT.class.cast(RESULT);
        ast.lineNumber = $$lineNumber;
    }
:}
```

## Notes
* Sorry about the spaces, Intellij fought me :(
* The name of the variables I created probably doesn't work well with your naming convention. 
* Didn't touch the changelog

### CODE REVIEW

**Comment by jhoenicke** [comment]
Thanks for your contribution.  

Can you add AFTER and REDUCE to symbol_id and robust_id in parser.cup? This way existing grammars using these as symbol names don't break. I believe there should be no ambiguity.

I think the after reduce code should be put into a function in the new code.  This helps code duplication and also to keep the do_action function small (there is the 64k opcode limit for a single function).  If I see it correctly, the function should take RESULT, $first and $last as arguments and return RESULT.
Here is a problem: what type should RESULT have?  Should this feature only be allowed if all nonterminals have the same type?

I know the indentation (2 spaces, braces on own line indented, tabs stands for 8 spaces) is quite peculiar, but please try to keep it for now.  Removing the trailing spaces in the cup file is not a problem.

**Comment by yoavst** [comment]
About formatting - I'll open an editor that doesn't force indentation on code and fix it.

You are right about the typing of `RESULT`. maybe it should be just a visitor, returning `void` instead.

I'll work on the change you proposed. In addition to those, maybe instead of defining $last and $first, maybe I should provide an array with all the tokens matched?

**Comment by yoavst** [comment]
@jhoenicke, Please take a look on the approach i've taken: an after reduce visitor (read only), that receives the result object in addition to symbols array.

**Comment by yoavst** [comment]
@jhoenicke Any update?

**Comment by jhoenicke** [comment]
I updated the indentation and used pre("symbol_array") for the symbol_array name (it should not be accessible by the user code, right?

Can you check if this still works, or if I broke something?

**Comment by jhoenicke** [comment]
Not sure if the after_reduce function should be void as it is now, or if it should be allowed to create a new RESULT though.  Your example only used side-effects to change RESULT.

**Comment by yoavst** [comment]
My example indeed only support side effects, but it is because I think the idea of this project it to provide type-safety on compile time. 

My code that depends on cup still works, so I assume the changes are OK.

**Pull request merged**
